name: DigiRestro
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cached network image for efficient image loading
  cached_network_image: ^3.3.1

  # Cupertino icons for iOS-style icons
  cupertino_icons: ^1.0.6

  # Equatable simplifies object comparison
  equatable: ^2.0.5

  # Firebase Packages for backend services
  cloud_firestore: ^4.16.1 # Firebase Firestore for NoSQL database
  firebase_auth: ^4.19.0 # Firebase Authentication for user management
  firebase_core: ^2.28.0 # Core Firebase functionalities
  firebase_database: ^10.5.2 # Firebase Realtime Database for structured data
  firebase_storage: ^11.7.2 # Firebase Storage for file uploads

  # Flutter Bloc for state management
  flutter_bloc: ^8.1.5

  # Dependency injection
  get_it: ^7.6.8

  # Google Fonts for custom typography
  google_fonts: ^6.2.1

  # Google Sign-In support
  google_sign_in: ^6.2.1

  # Spacing widgets
  gap: ^3.0.1

  # Internationalization and formatting utilities
  intl: ^0.19.0

  # Image Picker for picking images from gallery or camera
  image_picker: ^1.1.0

  # Shared Preferences for local storage
  shared_preferences: ^2.2.2

  # Loading shimmer effects for skeleton UI
  shimmer: ^3.0.0

  # SVG asset support
  flutter_svg: ^2.0.10+1

  # Flutter ScreenUtil for responsive layouts
  flutter_screenutil: ^5.9.0

  # Toast notifications
  fluttertoast: ^8.2.4

  # Customizable loading indicator
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter # For writing unit and widget tests

  # Linter rules for enforcing coding standards
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true # Ensures Material Design components are used

  # Directory for app assets
  assets:
    - lib/commons/assets/
